version: '3'
services:
  crypto-postgres:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./src/main/resources/database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
  crypto-tomcat:
    image: crypto-tomcat
    build: .
    pull_policy: never
    ports:
    -  8080:8080